import {getVertical,listVerticals} from './verticals.js';
import {tenantPrincipal,can} from './auth.js';
import {recommendOffers} from './offer-engine.js';
import {matchPartners,assignBestPartner} from './partner-match.js';
import {createProspect,issueDemoLink,demoProfile,listProspects} from './prospects.js';
import {buildProposal,latestProposal} from './proposals.js';
import {runProspectIntake,recommendDomains,listRecommendations} from './intake.js';
import {createBatch,listBatchRows,previewRow,approveRow,rejectRow,listBatches} from './factory.js';
import {buildPersonalBusiness,latestPersonalBusiness} from './personal-business.js';
import {bocobitesPilotBlueprint} from './pilot-bocobites.js';
import {alonaPilotBlueprint} from './pilot-alona.js';
const json=(x,s=200,extra={})=>new Response(JSON.stringify(x),{status:s,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store','x-content-type-options':'nosniff','referrer-policy':'strict-origin-when-cross-origin',...extra}});
const clean=v=>typeof v==='string'?v.trim():v;
async function hashHex(v){const b=new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(String(v||''))));return [...b].map(x=>x.toString(16).padStart(2,'0')).join('')}
async function rateLimit(env,request,tenant,bucket,limit,windowSeconds){
 const ip=request.headers.get('cf-connecting-ip')||'unknown';const key=await hashHex(`${env.RATE_LIMIT_SALT||tenant.id}:${ip}:${tenant.id}:${bucket}`);
 const now=Math.floor(Date.now()/1000),start=now-(now%windowSeconds);
 await env.DB.prepare(`INSERT INTO request_rate_limits(key,bucket,window_start,hits,updated_at) VALUES(?,?,?,?,?) ON CONFLICT(key,bucket,window_start) DO UPDATE SET hits=hits+1,updated_at=excluded.updated_at`).bind(key,bucket,start,1,new Date().toISOString()).run();
 const row=await env.DB.prepare(`SELECT hits FROM request_rate_limits WHERE key=? AND bucket=? AND window_start=?`).bind(key,bucket,start).first();
 if(Number(row?.hits||0)>limit)return json({error:'Too many requests. Please try again later.'},429,{'retry-after':String(windowSeconds-(now-start))});return null;
}
function bodyTooLarge(request,max=65536){const n=Number(request.headers.get('content-length')||0);return n>max}

async function tenantBySlug(env,slug){return env.DB.prepare("SELECT * FROM tenants WHERE slug=? AND status='active'").bind(slug).first()}
async function tenantFromRequest(env,request,body={}){const u=new URL(request.url),slug=body.tenant_slug||u.searchParams.get('tenant')||request.headers.get('x-tenant-slug');if(slug)return tenantBySlug(env,slug);return env.DB.prepare(`SELECT t.* FROM tenant_domains d JOIN tenants t ON t.id=d.tenant_id WHERE d.hostname=? AND t.status='active'`).bind(u.hostname.toLowerCase()).first()}
function settings(row){try{return JSON.parse(row?.settings_json||'{}')}catch{return{}}}
async function principalOr(env,request,tenant,roles){const p=await tenantPrincipal(request,env,tenant);return can(p,roles)?p:null}
export async function handleCoreApi(request,env){
 const u=new URL(request.url);if(!u.pathname.startsWith('/api/core/'))return null;
 if(u.pathname==='/api/core/verticals'&&request.method==='GET')return json({verticals:listVerticals()});
 let body={};if(['POST','PUT','PATCH'].includes(request.method)){if(bodyTooLarge(request))return json({error:'Request body too large'},413);try{body=await request.json()}catch{return json({error:'Invalid JSON'},400)}}
 const tenant=await tenantFromRequest(env,request,body);if(!tenant)return json({error:'Tenant not found'},404);const vertical=getVertical(tenant.vertical_slug),cfg=settings(tenant);
 if(u.pathname==='/api/core/config'&&request.method==='GET')return json({tenant:{slug:tenant.slug,name:tenant.name,domain:tenant.domain},vertical:{slug:vertical.slug,name:vertical.name},conversion_modes:vertical.conversion_modes,settings:cfg});
 if(u.pathname==='/api/core/pilots/bocobites'&&request.method==='GET'){const p=await principalOr(env,request,tenant,['owner','admin','sales']);if(!p)return json({error:'Unauthorized'},401);return json({pilot:bocobitesPilotBlueprint()});}
 if(u.pathname==='/api/core/pilots/alona'&&request.method==='GET'){const p=await principalOr(env,request,tenant,['owner','admin','sales']);if(!p)return json({error:'Unauthorized'},401);return json({pilot:alonaPilotBlueprint()});}
 if(u.pathname==='/api/core/advisor'&&request.method==='POST'){const limited=await rateLimit(env,request,tenant,'advisor',30,60);if(limited)return limited;const query=clean(body.query||'');if(!query)return json({error:'query is required'},400);const intent=vertical.parseIntent(query);let summary=`We identified your need as ${intent.intent_type}. Please confirm the key requirements before a commercial recommendation is made.`;if(env.AI){try{const o=await env.AI.run('@cf/meta/llama-3.1-8b-instruct',{messages:[{role:'system',content:vertical.systemPrompt},{role:'user',content:query}]});if(o?.response)summary=o.response}catch{}}const offers=await recommendOffers(env,tenant.id,intent.attributes||{});return json({tenant:tenant.slug,vertical:vertical.slug,intent,summary,offers:offers.slice(0,5)});}
 if(u.pathname==='/api/core/offers'&&request.method==='GET'){const attrs=Object.fromEntries([...u.searchParams.entries()].filter(([k])=>!['tenant'].includes(k)));return json({offers:await recommendOffers(env,tenant.id,attrs)});}
 if(u.pathname==='/api/core/lead'&&request.method==='POST'){const limited=await rateLimit(env,request,tenant,'lead',10,600);if(limited)return limited;if(!body.contact)return json({error:'contact is required'},400);const mode=body.conversion_mode||cfg.default_conversion_mode||vertical.conversion_modes[0]||'lead';if(!vertical.conversion_modes.includes(mode))return json({error:'Unsupported conversion mode'},400);const intent=body.query?vertical.parseIntent(body.query):{intent_type:body.intent_type||'general',attributes:{}};const attrs={...(intent.attributes||{}),...(body.attributes||{})},now=new Date().toISOString(),id=crypto.randomUUID();await env.DB.prepare(`INSERT INTO core_leads(id,tenant_id,name,company,contact,intent_type,conversion_mode,status,score,attributes_json,source_json,created_at,updated_at) VALUES(?,?,?,?,?,?,?,'new',?,?,?,?,?,?)`).bind(id,tenant.id,clean(body.name||''),clean(body.company||''),clean(body.contact),intent.intent_type,mode,Number(body.score||0),JSON.stringify(attrs),JSON.stringify(body.source||{}),now,now).run();const offers=await recommendOffers(env,tenant.id,attrs);let opportunity=null,assignment=null;if(offers[0]){const oid=crypto.randomUUID();await env.DB.prepare(`INSERT INTO opportunities(id,tenant_id,lead_id,offer_id,stage,score,attributes_json,next_action,created_at,updated_at) VALUES(?,?,?,?, 'qualified',?,?,?, ?,?)`).bind(oid,tenant.id,id,offers[0].id,Number(body.score||0),JSON.stringify(attrs),'Review and contact qualified lead',now,now).run();opportunity={id:oid,offer_id:offers[0].id,stage:'qualified'}}if(mode==='match')assignment=await assignBestPartner(env,tenant.id,id,attrs);return json({ok:true,id,tenant:tenant.slug,vertical:vertical.slug,intent_type:intent.intent_type,conversion_mode:mode,recommended_offers:offers.slice(0,3),opportunity,partner_assignment:assignment},201);}
 if(u.pathname==='/api/core/partner-match'&&request.method==='POST'){const p=await principalOr(env,request,tenant,['owner','admin','sales']);if(!p)return json({error:'Unauthorized'},401);const attrs=body.attributes||{};return json({matches:await matchPartners(env,tenant.id,attrs,5)});}
 if(u.pathname==='/api/core/demo'&&request.method==='GET'){const d=await demoProfile(env,tenant.id,u.searchParams.get('token')||'');if(!d)return json({error:'Demo link not found or expired'},404);const offers=await recommendOffers(env,tenant.id,d.prospect.audience||{});const proposal=await latestProposal(env,tenant.id,d.prospect.id);const business=await latestPersonalBusiness(env,tenant.id,d.prospect.id);return json({...d,tenant:{slug:tenant.slug,name:tenant.name,domain:tenant.domain},vertical:{slug:vertical.slug,name:vertical.name},settings:cfg,offers:offers.slice(0,5),proposal,business});}
 if(u.pathname==='/api/core/opportunity'&&request.method==='POST'){const p=await principalOr(env,request,tenant,['owner','admin','sales']);if(!p)return json({error:'Unauthorized'},401);const {analyzeBusinessOpportunity}=await import('./opportunity-engine.js');return json({opportunity:analyzeBusinessOpportunity(body)});}
 if(u.pathname==='/api/core/domain-recommendations'&&request.method==='POST'){const p=await principalOr(env,request,tenant,['owner','admin','sales']);if(!p)return json({error:'Unauthorized'},401);return json({recommendations:await recommendDomains(env,body,body.limit||5),notice:'Rule-based recommendations from declared profile data; manual review required.'});}
 if(u.pathname==='/api/core/prospect-intake'&&request.method==='POST'){const p=await principalOr(env,request,tenant,['owner','admin','sales']);if(!p)return json({error:'Unauthorized'},401);if(!body.name&&!body.company)return json({error:'name or company is required'},400);return json({ok:true,...await runProspectIntake(env,tenant,body)},201);}
 if(u.pathname==='/api/core/prospect-recommendations'&&request.method==='GET'){const p=await principalOr(env,request,tenant,['owner','admin','sales']);if(!p)return json({error:'Unauthorized'},401);const prospectId=u.searchParams.get('prospect_id');if(!prospectId)return json({error:'prospect_id is required'},400);return json({recommendations:await listRecommendations(env,tenant.id,prospectId)});}
 if(u.pathname==='/api/core/factory/batches'&&request.method==='GET'){const p=await principalOr(env,request,tenant,['owner','admin','sales']);if(!p)return json({error:'Unauthorized'},401);return json({batches:await listBatches(env,tenant.id)});}
 if(u.pathname==='/api/core/factory/batch'&&request.method==='POST'){const p=await principalOr(env,request,tenant,['owner','admin','sales']);if(!p)return json({error:'Unauthorized'},401);try{return json({ok:true,batch:await createBatch(env,tenant,body)},201)}catch(e){return json({error:e.message||'Batch import failed'},400)}}
 if(u.pathname==='/api/core/factory/rows'&&request.method==='GET'){const p=await principalOr(env,request,tenant,['owner','admin','sales']);if(!p)return json({error:'Unauthorized'},401);const id=u.searchParams.get('batch_id');if(!id)return json({error:'batch_id is required'},400);return json({rows:await listBatchRows(env,tenant.id,id)});}
 if(u.pathname==='/api/core/factory/preview'&&request.method==='GET'){const p=await principalOr(env,request,tenant,['owner','admin','sales']);if(!p)return json({error:'Unauthorized'},401);const id=u.searchParams.get('row_id');const out=await previewRow(env,tenant.id,id);return out?json(out):json({error:'Row not found'},404);}
 if(u.pathname==='/api/core/factory/approve'&&request.method==='POST'){const p=await principalOr(env,request,tenant,['owner','admin','sales']);if(!p)return json({error:'Unauthorized'},401);if(!body.row_id)return json({error:'row_id is required'},400);try{return json({ok:true,result:await approveRow(env,tenant,body.row_id,body,p)})}catch(e){return json({error:e.message||'Approval failed'},400)}}
 if(u.pathname==='/api/core/factory/reject'&&request.method==='POST'){const p=await principalOr(env,request,tenant,['owner','admin','sales']);if(!p)return json({error:'Unauthorized'},401);if(!body.row_id)return json({error:'row_id is required'},400);return json(await rejectRow(env,tenant.id,body.row_id,body.note||''));}
 if(u.pathname==='/api/core/prospects'&&request.method==='GET'){const p=await principalOr(env,request,tenant,['owner','admin','sales']);if(!p)return json({error:'Unauthorized'},401);return json({prospects:await listProspects(env,tenant.id)});}
 if(u.pathname==='/api/core/prospects'&&request.method==='POST'){const p=await principalOr(env,request,tenant,['owner','admin','sales']);if(!p)return json({error:'Unauthorized'},401);if(!body.name&&!body.company)return json({error:'name or company is required'},400);return json({ok:true,...await createProspect(env,tenant.id,body)},201);}
 if(u.pathname==='/api/core/personal-business'&&request.method==='POST'){const p=await principalOr(env,request,tenant,['owner','admin','sales']);if(!p)return json({error:'Unauthorized'},401);if(!body.prospect_id)return json({error:'prospect_id is required'},400);const out=await buildPersonalBusiness(env,tenant,body.prospect_id,body);return out?json({ok:true,business:out},201):json({error:'Prospect not found'},404);}
 if(u.pathname==='/api/core/proposal'&&request.method==='POST'){const p=await principalOr(env,request,tenant,['owner','admin','sales']);if(!p)return json({error:'Unauthorized'},401);if(!body.prospect_id)return json({error:'prospect_id is required'},400);const proposal=await buildProposal(env,tenant,body.prospect_id,body);if(!proposal)return json({error:'Prospect not found'},404);return json({ok:true,proposal},201);}
 if(u.pathname==='/api/core/demo-link'&&request.method==='POST'){const p=await principalOr(env,request,tenant,['owner','admin','sales']);if(!p)return json({error:'Unauthorized'},401);if(!body.prospect_id)return json({error:'prospect_id is required'},400);const d=await issueDemoLink(env,tenant.id,body.prospect_id,body.days||14);return json({ok:true,...d,demo_path:`/prospect-demo.html?tenant=${encodeURIComponent(tenant.slug)}&token=${encodeURIComponent(d.token)}`},201);}
 if(u.pathname==='/api/core/partners'&&request.method==='GET'){const p=await principalOr(env,request,tenant,['owner','admin','sales']);if(!p)return json({error:'Unauthorized'},401);const r=await env.DB.prepare(`SELECT id,name,partner_type,email,company,status,capabilities_json,audience_json,commercial_json FROM tenant_partners WHERE tenant_id=? ORDER BY name`).bind(tenant.id).all();return json({partners:r.results||[]});}
 if(u.pathname==='/api/core/partners'&&request.method==='POST'){const p=await principalOr(env,request,tenant,['owner','admin']);if(!p)return json({error:'Unauthorized'},401);if(!body.name)return json({error:'name is required'},400);const id=crypto.randomUUID(),now=new Date().toISOString();await env.DB.prepare(`INSERT INTO tenant_partners(id,tenant_id,name,partner_type,email,company,status,capabilities_json,audience_json,commercial_json,created_at,updated_at) VALUES(?,?,?,?,?,?,'active',?,?,?,?,?)`).bind(id,tenant.id,clean(body.name),clean(body.partner_type||'provider'),clean(body.email||''),clean(body.company||''),JSON.stringify(body.capabilities||{}),JSON.stringify(body.audience||{}),JSON.stringify(body.commercial||{}),now,now).run();return json({ok:true,id},201);}
 return json({error:'Core route not found'},404);
}
