import {recommendDomains,runProspectIntake} from './intake.js';
const clean=v=>String(v??'').trim();
const norm=v=>clean(v).toLowerCase().normalize('NFKD').replace(/[^a-z0-9@.+]+/g,' ').trim();
function normEmail(v){return clean(v).toLowerCase()}
function normProfile(v){let x=clean(v).toLowerCase();if(!x)return '';try{const u=new URL(/^https?:\/\//.test(x)?x:'https://'+x);let h=u.hostname.replace(/^www\./,'');let path=u.pathname.replace(/\/+$/,'');if(h==='linkedin.com'||h.endsWith('.linkedin.com')){path=path.replace(/\/+$/,'');return 'linkedin.com'+path}return h+path}catch{return x.split('?')[0].split('#')[0].replace(/\/+$/,'')}}
const hex=b=>[...b].map(x=>x.toString(16).padStart(2,'0')).join('');
async function hash(v){return hex(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(v))))}
function arr(v){if(Array.isArray(v))return v;return clean(v).split(/[;,|]/).map(x=>x.trim()).filter(Boolean)}
function normalizedRow(r={}){return {name:clean(r.name||r.full_name),company:clean(r.company),role:clean(r.role||r.title),industry:clean(r.industry),profile_url:clean(r.profile_url||r.linkedin||r.linkedin_url),email:clean(r.email),markets:arr(r.markets||r.market),tags:arr(r.tags),bio:clean(r.bio),notes:clean(r.notes),audience:{followers:Number(r.followers||r.audience_size||0)||0,engagement:Number(r.engagement||0)||0}}}
async function fingerprint(r){const strong=normProfile(r.profile_url)||normEmail(r.email);const fallback=[norm(r.name),norm(r.company),norm(r.role)].join('|');return hash(strong||fallback)}
export async function createBatch(env,tenant,b={}){
 const rows=Array.isArray(b.rows)?b.rows:[];if(!rows.length)throw new Error('rows are required');if(rows.length>1000)throw new Error('Maximum 1000 rows per batch');
 const id=crypto.randomUUID(),now=new Date().toISOString();let dup=0,accepted=0;
 await env.DB.prepare(`INSERT INTO prospect_batches(id,tenant_id,name,source,status,total_rows,created_at,updated_at) VALUES(?,?,?,?, 'review',?,?,?)`).bind(id,tenant.id,clean(b.name||`Prospect batch ${now.slice(0,10)}`),clean(b.source||'csv'),rows.length,now,now).run();
 for(let i=0;i<rows.length;i++){
  const r=normalizedRow(rows[i]),fp=await fingerprint(r);let status='pending',duplicateOf=null;
  const prior=await env.DB.prepare(`SELECT id,prospect_id FROM prospect_batch_rows WHERE tenant_id=? AND fingerprint=? ORDER BY created_at LIMIT 1`).bind(tenant.id,fp).first();
  const profileKey=normProfile(r.profile_url),emailKey=normEmail(r.email);let existing=null;
  if(profileKey){const ph=await hash(profileKey);existing=await env.DB.prepare(`SELECT prospect_id,batch_row_id FROM prospect_identity_keys WHERE tenant_id=? AND key_type='profile' AND key_value_hash=? LIMIT 1`).bind(tenant.id,ph).first();}
  if(!existing&&emailKey){const eh=await hash(emailKey);existing=await env.DB.prepare(`SELECT prospect_id,batch_row_id FROM prospect_identity_keys WHERE tenant_id=? AND key_type='email' AND key_value_hash=? LIMIT 1`).bind(tenant.id,eh).first();}
  if(prior||existing){status='duplicate';duplicateOf=prior?.id||existing?.batch_row_id||existing?.prospect_id||null;dup++;}
  else accepted++;
  await env.DB.prepare(`INSERT INTO prospect_batch_rows(id,batch_id,tenant_id,row_number,fingerprint,input_json,status,duplicate_of,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?)`).bind(crypto.randomUUID(),id,tenant.id,i+1,fp,JSON.stringify(r),status,duplicateOf,now,now).run();
 }
 await env.DB.prepare(`UPDATE prospect_batches SET accepted_rows=?,duplicate_rows=?,updated_at=? WHERE id=?`).bind(accepted,dup,now,id).run();return{id,total_rows:rows.length,pending:accepted,duplicates:dup};
}
export async function listBatchRows(env,tenantId,batchId){const r=await env.DB.prepare(`SELECT id,row_number,input_json,status,duplicate_of,prospect_id,selected_domain,selected_business_model,fit_score,review_note,approved_at FROM prospect_batch_rows WHERE tenant_id=? AND batch_id=? ORDER BY row_number`).bind(tenantId,batchId).all();return (r.results||[]).map(x=>({...x,input:JSON.parse(x.input_json||'{}')}))}
export async function previewRow(env,tenantId,rowId){const row=await env.DB.prepare(`SELECT * FROM prospect_batch_rows WHERE tenant_id=? AND id=?`).bind(tenantId,rowId).first();if(!row)return null;const input=JSON.parse(row.input_json||'{}');return{row:{id:row.id,row_number:row.row_number,status:row.status,input},recommendations:await recommendDomains(env,input,5)}}
function outreachText(p,domain,model,demoPath){const who=p.name||p.company||'there';return `Hi ${who}, thank you for connecting. I looked at your business and prepared a concrete ${model||'digital business'} concept around ${domain}. Rather than a standard domain sale, I can contribute the premium domain, AI platform and technology; your side can be audience, expertise and distribution. I prepared a private working proposal for you: ${demoPath} — Thank you Michal Doubek, Diar.ai`;}
export async function approveRow(env,tenant,rowId,b={},principal=null){
 const row=await env.DB.prepare(`SELECT * FROM prospect_batch_rows WHERE tenant_id=? AND id=?`).bind(tenant.id,rowId).first();if(!row)return null;if(row.status==='approved')throw new Error('Row is already approved');if(row.status==='processing')throw new Error('Row approval is already processing');if(row.status==='duplicate')throw new Error('Duplicate row must be resolved before approval');
 const lock=await env.DB.prepare(`UPDATE prospect_batch_rows SET status='processing',processing_started_at=?,updated_at=? WHERE id=? AND tenant_id=? AND status='pending'`).bind(new Date().toISOString(),new Date().toISOString(),rowId,tenant.id).run();if(!lock.meta?.changes)throw new Error('Row is not in an approvable state');
 const input=JSON.parse(row.input_json||'{}'),recs=await recommendDomains(env,input,10);const selected=(b.domain_name&&recs.find(x=>x.domain_name===b.domain_name))||recs[0];if(!selected)throw new Error('No domain recommendation available');
 const result=await runProspectIntake(env,tenant,{...input,source:'prospect-factory',demo_days:Number(b.demo_days||14)});const chosen=result.recommendations.find(x=>x.domain_name===selected.domain_name)||result.recommendations[0];
 const now=new Date().toISOString(),demoPath=result.demo?.demo_path||'',original=JSON.stringify(recs[0]||null),finalSel=JSON.stringify(chosen||selected),opp=JSON.stringify((chosen||selected).opportunity||{});const text=outreachText(input,chosen?.domain_name||selected.domain_name,chosen?.business_model||selected.business_model,demoPath);
 await env.DB.prepare(`UPDATE prospect_batch_rows SET status='approved',prospect_id=?,selected_domain=?,selected_business_model=?,fit_score=?,review_note=?,approved_by=?,original_recommendation_json=?,final_selection_json=?,opportunity_json=?,approved_at=?,updated_at=? WHERE id=? AND tenant_id=?`).bind(result.prospect.id,chosen?.domain_name||selected.domain_name,chosen?.business_model||selected.business_model,chosen?.fit_score||selected.fit_score,clean(b.review_note),principal?.email||principal?.member_id||'unknown',original,finalSel,opp,now,now,rowId,tenant.id).run();
 const keys=[['profile',normProfile(input.profile_url)],['email',normEmail(input.email)]].filter(x=>x[1]);for(const [type,val] of keys){const hv=await hash(val);await env.DB.prepare(`INSERT OR IGNORE INTO prospect_identity_keys(id,tenant_id,prospect_id,batch_row_id,key_type,key_value_hash,normalized_hint,created_at) VALUES(?,?,?,?,?,?,?,?)`).bind(crypto.randomUUID(),tenant.id,result.prospect.id,rowId,type,hv,type==='email'?val.replace(/^(.{2}).*(@.*)$/,'$1***$2'):val,now).run();}
 await env.DB.prepare(`INSERT INTO audit_log(id,entity_type,entity_id,action,actor_type,actor_id,meta_json) VALUES(?,?,?,?,?,?,?)`).bind(crypto.randomUUID(),'prospect_batch_row',rowId,'approved','tenant_member',principal?.member_id||null,JSON.stringify({selected_domain:chosen?.domain_name||selected.domain_name,business_model:chosen?.business_model||selected.business_model,fit_score:chosen?.fit_score||selected.fit_score})).run();
 await env.DB.prepare(`INSERT INTO prospect_outreach_drafts(id,tenant_id,prospect_id,batch_row_id,channel,language,body,status,created_at,updated_at) VALUES(?,?,?,?,?,'en',?,'draft',?,?)`).bind(crypto.randomUUID(),tenant.id,result.prospect.id,rowId,clean(b.channel||'linkedin'),text,now,now).run();return{...result,selected:chosen||selected,outreach_draft:text};
}
export async function rejectRow(env,tenantId,rowId,note=''){const now=new Date().toISOString();await env.DB.prepare(`UPDATE prospect_batch_rows SET status='rejected',review_note=?,updated_at=? WHERE id=? AND tenant_id=?`).bind(clean(note),now,rowId,tenantId).run();return{ok:true}}
export async function listBatches(env,tenantId){const r=await env.DB.prepare(`SELECT * FROM prospect_batches WHERE tenant_id=? ORDER BY created_at DESC LIMIT 50`).bind(tenantId).all();return r.results||[]}
