import {assessAudience} from './audience.js';
const clean=v=>typeof v==='string'?v.trim():v;
const parse=v=>{try{return JSON.parse(v||'{}')}catch{return{}}};
const slugify=v=>String(v||'prospect').toLowerCase().normalize('NFKD').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,60)||'prospect';
const hex=bytes=>[...bytes].map(x=>x.toString(16).padStart(2,'0')).join('');
async function hash(v){return hex(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(String(v||'')))))}
function token(){const b=crypto.getRandomValues(new Uint8Array(24));return btoa(String.fromCharCode(...b)).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')}
export async function createProspect(env,tenantId,b={}){
 const id=crypto.randomUUID(),now=new Date().toISOString(),base=slugify(b.slug||b.name||b.company),slug=`${base}-${id.slice(0,6)}`;
 const audience=b.audience||{},assessment=assessAudience(audience);
 await env.DB.prepare(`INSERT INTO prospect_profiles(id,tenant_id,slug,name,company,role,audience_json,contribution_json,preferred_offer_id,status,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,'active',?,?)`).bind(id,tenantId,slug,clean(b.name||b.company||'Prospect'),clean(b.company||''),clean(b.role||''),JSON.stringify(audience),JSON.stringify(b.contribution||{}),b.preferred_offer_id||null,now,now).run();
 await env.DB.prepare(`INSERT INTO audience_assessments(id,tenant_id,prospect_id,score,band,factors_json,reasons_json,created_at) VALUES(?,?,?,?,?,?,?,?)`).bind(crypto.randomUUID(),tenantId,id,assessment.score,assessment.band,JSON.stringify(assessment.factors),JSON.stringify(assessment.reasons),now).run();
 return{id,slug,assessment};
}
export async function issueDemoLink(env,tenantId,prospectId,days=14){const raw=token(),h=await hash(raw),id=crypto.randomUUID(),now=new Date(),exp=new Date(now.getTime()+Math.max(1,Number(days)||14)*86400000).toISOString();await env.DB.prepare(`INSERT INTO demo_links(id,tenant_id,prospect_id,token_hash,expires_at,created_at) VALUES(?,?,?,?,?,?)`).bind(id,tenantId,prospectId,h,exp,now.toISOString()).run();return{id,token:raw,expires_at:exp}}
export async function demoProfile(env,tenantId,raw){if(!raw)return null;const h=await hash(raw);const row=await env.DB.prepare(`SELECT p.*,a.score audience_score,a.band audience_band,a.factors_json,a.reasons_json,d.id demo_link_id FROM demo_links d JOIN prospect_profiles p ON p.id=d.prospect_id LEFT JOIN audience_assessments a ON a.id=(SELECT aa.id FROM audience_assessments aa WHERE aa.prospect_id=p.id ORDER BY aa.created_at DESC LIMIT 1) WHERE d.token_hash=? AND d.tenant_id=? AND d.revoked_at IS NULL AND (d.expires_at IS NULL OR datetime(d.expires_at)>datetime('now')) AND p.status='active'`).bind(h,tenantId).first();if(!row)return null;await env.DB.prepare('UPDATE demo_links SET last_opened_at=CURRENT_TIMESTAMP WHERE id=?').bind(row.demo_link_id).run();return{prospect:{id:row.id,slug:row.slug,name:row.name,company:row.company,role:row.role,audience:parse(row.audience_json),contribution:parse(row.contribution_json),preferred_offer_id:row.preferred_offer_id},assessment:{score:Number(row.audience_score||0),band:row.audience_band||'D',factors:parse(row.factors_json),reasons:parse(row.reasons_json)}}}
export async function listProspects(env,tenantId){const r=await env.DB.prepare(`SELECT p.id,p.slug,p.name,p.company,p.role,p.status,p.updated_at,a.score audience_score,a.band audience_band FROM prospect_profiles p LEFT JOIN audience_assessments a ON a.id=(SELECT aa.id FROM audience_assessments aa WHERE aa.prospect_id=p.id ORDER BY aa.created_at DESC LIMIT 1) WHERE p.tenant_id=? ORDER BY p.updated_at DESC LIMIT 200`).bind(tenantId).all();return r.results||[]}
